### ISSUE TITLE
Escape character rendering issue

### ISSUE THREAD

**Issue by ltagliaferri** [LiaBooks/How-To-Code-in-Python-3#1]
It looks like LiaScript is introducing extra slashes in the **Escape Characters** section, and is causing an error if you try to run it. 

<img width="1116" alt="Screen Shot 2022-06-08 at 12 45 55 PM" src="https://user-images.githubusercontent.com/5977693/172683127-9e4daf3c-2c10-445f-a61d-7e088a8d85bf.png">

The examples should read like this:

```py
print("Sammy says, \"Hello!\"")
```

```py
print('Sammy\'s balloon is red.')
```

**Comment by andre-dietrich** [comment]
Hi, thanks for the report, I fixed this within the newest version ... It seems to be a PyScript-bug, which is related to this one  

https://github.com/pyscript/pyscript/pull/481#issuecomment-1145122835
